feat:add cache for the g(_, _) function.
php-casbin/php-casbin pull request #139
Opened 2022-08-05 13:55 UTC by M1serry

2022-08-05 14:57 UTC, hsluoyz commented
@leeqvip

2022-08-06 15:41 UTC, leeqvip commented
@M1serry Some checks were not successful, fix please.

2022-08-09 01:36 UTC, leeqvip requested changes
Unit test failed, please fix

2022-08-15 13:01 UTC, leeqvip requested changes

2022-08-16 16:42 UTC, leeqvip commented on src/Util/BuiltinOperations.php
> +            }
@M1serry See suggested change .

2022-08-24 14:40 UTC, leeqvip requested changes

2022-08-24 14:40 UTC, leeqvip commented on src/Util/BuiltinOperations.php
> +            $memorized = [];
` $memorized` should be defined outside.

2022-08-24 15:21 UTC, leeqvip commented on src/Util/BuiltinOperations.php
> +
```suggestion
            /** @phpstan-ignore-next-line */
```

2022-08-24 15:23 UTC, merged