feat: Implement CachedEnforcer with Symfony Cache component
php-casbin/php-casbin pull request #162
Opened 2024-09-12 09:51 UTC by Dobmod

- Added CachedEnforcer to integrate Symfony's Cache component for caching functionality.
- Enabled support for multiple cache adapters, allowing flexible switching based on configuration.
- Added methods to control cache usage, improving flexibility and performance in caching decisions.

2024-09-13 16:06 UTC, leeqvip requested changes

2024-09-13 16:06 UTC, leeqvip commented on src/CachedEnforcer.php
> +        $this->cache = new FilesystemAdapter(namespace: uniqid('casbin_cache_'));
Please use ArrayAdapter by default

2024-09-14 09:30 UTC, Dobmod commented on src/CachedEnforcer.php
> +    protected $cache;
If defining attribute type, I think it is best to cover all classes. 
All will be completed in the next PR, and strict attribute declarations will trigger new errors.

2024-09-14 16:36 UTC, leeqvip approved these changes

2024-09-14 16:36 UTC, merged

2024-10-21 16:10 UTC, leeqvip commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/php-casbin/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: