refactor: Split RoleManager into DomainManager
php-casbin/php-casbin pull request #165
Opened 2024-09-25 17:31 UTC by Dobmod

- Maintain consistency with core library 
  - Prepare for RBAC with Conditions 
  - Standardize styles (e.g., Closure, count) 
  - Improve unit tests

2024-09-29 10:24 UTC, leeqvip requested changes

2024-09-29 10:24 UTC, leeqvip commented on src/Rbac/DefaultRoleManager/RoleManager.php
> +        foreach ($users as $_ => &$user) {
Why not just omit it?
```
 foreach ($users as &$user) {
```

2024-09-29 10:24 UTC, leeqvip commented on src/Rbac/DefaultRoleManager/Traits/DomainManager.php
> +    public function getDomain(string ...$domains): string
Please use the default value directly
```
public function getDomain(?string $domain = null): string
```

2024-09-29 16:11 UTC, Dobmod commented on src/Rbac/DefaultRoleManager/Role.php
> +        return $names;
This must use `use` to pass references, and `arrow functions` cannot modify references to external variables. 😊

2024-09-30 03:18 UTC, leeqvip approved these changes

2024-09-30 03:18 UTC, merged

2024-10-21 16:09 UTC, leeqvip commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/php-casbin/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: