feat: support enforceEx, fix #70
php-casbin/php-casbin pull request #72
Opened 2021-04-11 13:49 UTC by basakest

2021-04-11 13:58 UTC, hsluoyz commented
@techoner

2021-04-11 15:23 UTC, techoner requested changes

2021-04-11 15:23 UTC, techoner commented on src/CoreEnforcer.php
> +            $reqStr .= sprintf("---> %s\n", (string)$result);
Please keep spaces in the log:
```
$reqStr .= sprintf(" ---> %s\n", var_export($result, true);
```

2021-04-11 15:23 UTC, techoner commented on src/CoreEnforcer.php
> +                    $reqStr .= sprintf("%s \n", (string)$pval);
Print the array like this :
```
$reqStr .= sprintf("%s \n", '['.implode(', ',$pval).']');
```

2021-05-26 12:42 UTC, merged

2021-05-26 12:44 UTC, techoner commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/php-casbin/releases/tag/v3.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: