fix: MergeEffects cannot return right value, fix #79
php-casbin/php-casbin pull request #80
Opened 2021-06-22 07:01 UTC by basakest

fix: #79

2021-06-22 11:58 UTC, hsluoyz commented
@mmehira plz review.

2021-06-22 13:13 UTC, mmehira commented
@hsluoyz just tested locally with the same conf and policy files. Everything is working as expected. 

Good job! Thanks a lot for this fix.

2021-06-22 15:07 UTC, hsluoyz commented
@techoner

2021-06-23 04:18 UTC, techoner requested changes

2021-06-23 04:18 UTC, techoner commented on src/Effect/DefaultEffector.php
>              }
@basakest This can be a `for` loop, just one loop, avoid using `array_search` twice .

2021-06-27 03:20 UTC, techoner approved these changes

2021-06-27 03:20 UTC, merged

2021-06-27 03:22 UTC, techoner commented
:tada: This PR is included in version 3.3.1 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/php-casbin/releases/tag/v3.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: