feat: support buildIncrementalRoleLinks, fix #73
php-casbin/php-casbin pull request #87
Opened 2021-07-18 08:39 UTC by basakest

fix #73

2021-07-18 15:36 UTC, hsluoyz commented
@techoner

2021-07-19 08:57 UTC, techoner requested changes

2021-07-19 08:57 UTC, techoner commented on src/InternalEnforcer.php
> +            $this->buildIncrementalRoleLinks(Policy::POLICY_ADD, $ptype, $rules);
It can be a bit concise here :
```
$this->buildIncrementalRoleLinks(Policy::POLICY_ADD, $ptype, [$rule]);
```

2021-07-19 08:57 UTC, techoner commented on src/InternalEnforcer.php
> +                $this->buildIncrementalRoleLinks(Policy::POLICY_REMOVE, $ptype, $oldRules);
```
$this->buildIncrementalRoleLinks(Policy::POLICY_ADD, $ptype, [oldRule]);
```
Write like this, the following is the same, and then remove the `try catch `.

2021-07-19 08:57 UTC, techoner commented on src/InternalEnforcer.php
> +    }
Move it to `CoreEnforcer`.

2021-07-20 09:40 UTC, techoner approved these changes

2021-07-20 09:40 UTC, merged

2021-07-20 09:42 UTC, techoner commented
:tada: This PR is included in version 3.5.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/php-casbin/releases/tag/v3.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: